### ISSUE TITLE
Rubocop

### ISSUE THREAD

**Issue by stejskalleos** [nofaralfasi/todo_list#7]
Use [Rubocop](https://github.com/rubocop/rubocop) static code analyzer

**Comment by nofaralfasi** [comment]
I added Rubocop to my application, but I am not sure if I should fix some of its errors.
For example:
1. Missing frozen string literal comment.
2. Do not prefix reader method names with get_.
3. Use a guard clause instead of wrapping the code inside a conditional expression.
And so on.. So right now I'm fixing the errors that make sense to me.

**Comment by stejskalleos** [comment]
All of these mentioned issues should be fixed, but right now focus on the issues that make sense for you and the rest we can discuss later.

And one thing, I would definitely create special PR for it, do not add the changes to current PR, we should follow rule
one PR = one feature.

**Comment by nofaralfasi** [comment]
Got it, thanks Leos!
